---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.6.130
    jenkins-agent-01:
      ansible_host: 51.250.88.241
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01: 51.250.6.130
        jenkins_agents:
          hosts:
              jenkins-agent-01: 51.250.88.241
  vars:
    ansible_user: root
    ansible_connection_type: paramiko
    ansible_ssh_private_key_file: /root/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python